/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author USER1
 */
public class Calculator extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    String operations;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btn_seven = new javax.swing.JButton();
        btn_four = new javax.swing.JButton();
        btn_one = new javax.swing.JButton();
        btn_eight = new javax.swing.JButton();
        btn_five = new javax.swing.JButton();
        btn_two = new javax.swing.JButton();
        btn_nine = new javax.swing.JButton();
        btn_six = new javax.swing.JButton();
        btn_three = new javax.swing.JButton();
        btn_multi = new javax.swing.JButton();
        btn_rest = new javax.swing.JButton();
        btn_sum = new javax.swing.JButton();
        btn_divi = new javax.swing.JButton();
        btn_equal = new javax.swing.JButton();
        btn_point = new javax.swing.JButton();
        btn_zero = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        txt_formula = new javax.swing.JTextField();
        txt_result = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_seven.setBackground(new java.awt.Color(204, 204, 204));
        btn_seven.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_seven.setText("7");
        btn_seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sevenActionPerformed(evt);
            }
        });

        btn_four.setBackground(new java.awt.Color(204, 204, 204));
        btn_four.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_four.setText("4");
        btn_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fourActionPerformed(evt);
            }
        });

        btn_one.setBackground(new java.awt.Color(204, 204, 204));
        btn_one.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_one.setText("1");
        btn_one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_oneMousePressed(evt);
            }
        });
        btn_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oneActionPerformed(evt);
            }
        });

        btn_eight.setBackground(new java.awt.Color(204, 204, 204));
        btn_eight.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_eight.setText("8");
        btn_eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eightActionPerformed(evt);
            }
        });

        btn_five.setBackground(new java.awt.Color(204, 204, 204));
        btn_five.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_five.setText("5");
        btn_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fiveActionPerformed(evt);
            }
        });

        btn_two.setBackground(new java.awt.Color(204, 204, 204));
        btn_two.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_two.setText("2");
        btn_two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_twoMousePressed(evt);
            }
        });
        btn_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_twoActionPerformed(evt);
            }
        });

        btn_nine.setBackground(new java.awt.Color(204, 204, 204));
        btn_nine.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_nine.setText("9");
        btn_nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nineActionPerformed(evt);
            }
        });

        btn_six.setBackground(new java.awt.Color(204, 204, 204));
        btn_six.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_six.setText("6");
        btn_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sixActionPerformed(evt);
            }
        });

        btn_three.setBackground(new java.awt.Color(204, 204, 204));
        btn_three.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_three.setText("3");
        btn_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_threeActionPerformed(evt);
            }
        });

        btn_multi.setBackground(new java.awt.Color(255, 102, 0));
        btn_multi.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_multi.setForeground(new java.awt.Color(255, 255, 255));
        btn_multi.setText("*");
        btn_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiActionPerformed(evt);
            }
        });

        btn_rest.setBackground(new java.awt.Color(255, 102, 0));
        btn_rest.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_rest.setForeground(new java.awt.Color(255, 255, 255));
        btn_rest.setText("-");
        btn_rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restActionPerformed(evt);
            }
        });

        btn_sum.setBackground(new java.awt.Color(255, 102, 0));
        btn_sum.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_sum.setForeground(new java.awt.Color(255, 255, 255));
        btn_sum.setText("+");
        btn_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumActionPerformed(evt);
            }
        });

        btn_divi.setBackground(new java.awt.Color(255, 102, 0));
        btn_divi.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_divi.setForeground(new java.awt.Color(255, 255, 255));
        btn_divi.setText("/");
        btn_divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diviActionPerformed(evt);
            }
        });

        btn_equal.setBackground(new java.awt.Color(255, 102, 0));
        btn_equal.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_equal.setForeground(new java.awt.Color(255, 255, 255));
        btn_equal.setText("=");
        btn_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalActionPerformed(evt);
            }
        });

        btn_point.setBackground(new java.awt.Color(204, 204, 204));
        btn_point.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_point.setText(".");
        btn_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pointActionPerformed(evt);
            }
        });

        btn_zero.setBackground(new java.awt.Color(204, 204, 204));
        btn_zero.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        btn_zero.setText("0");
        btn_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zeroActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(51, 204, 255));
        btn_clear.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(51, 204, 255));
        btn_reset.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        txt_formula.setBackground(new java.awt.Color(153, 153, 153));
        txt_formula.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        txt_formula.setForeground(new java.awt.Color(255, 255, 255));
        txt_formula.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_result.setBackground(new java.awt.Color(153, 153, 153));
        txt_result.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        txt_result.setForeground(new java.awt.Color(255, 255, 255));
        txt_result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_one, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_two, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_three, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_zero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_point, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_four, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_five, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_six, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_formula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_result, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_divi, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                        .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_rest, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_formula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_divi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_rest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_result, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_four, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_five, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_six, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_one, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_two, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_three, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_point, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eightActionPerformed
        String Enternumber = txt_result.getText() + btn_eight.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eightActionPerformed

    private void btn_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_threeActionPerformed
        String Enternumber = txt_result.getText() + btn_three.getText();
        txt_result.setText(Enternumber);        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_threeActionPerformed

    private void btn_diviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diviActionPerformed
        firstnum = Double.parseDouble(txt_result.getText());
        txt_result.setText("");
        operations="/";
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_diviActionPerformed

    private void btn_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalActionPerformed
        String answer;
        secondnum = Double.parseDouble(txt_result.getText());
        if(operations == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.0f",result);
            txt_result.setText(answer);
            txt_formula.setText(String.valueOf(firstnum)+("+")+(secondnum));
        }
        else if (operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.0f",result);
            txt_result.setText(answer);
            txt_formula.setText(String.valueOf(firstnum)+("-")+(secondnum));
        }
        else if (operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.0f",result);
            txt_result.setText(answer);
            txt_formula.setText(String.valueOf(firstnum)+("/")+(secondnum));
        }
        else if (operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.0f",result);
            txt_result.setText(answer);
            txt_formula.setText(String.valueOf(firstnum)+("*")+(secondnum));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_equalActionPerformed

    private void btn_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pointActionPerformed
        String Enternumber = txt_result.getText() + btn_point.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pointActionPerformed

    private void btn_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zeroActionPerformed
        String Enternumber = txt_result.getText() + btn_zero.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_zeroActionPerformed

    private void btn_oneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_oneMousePressed

// TODO add your handling code here:
    }//GEN-LAST:event_btn_oneMousePressed

    private void btn_twoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_twoMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_twoMousePressed

    private void btn_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oneActionPerformed
        String Enternumber = txt_result.getText() + btn_one.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_oneActionPerformed

    private void btn_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_twoActionPerformed
        String Enternumber = txt_result.getText() + btn_two.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_twoActionPerformed

    private void btn_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fourActionPerformed
        String Enternumber = txt_result.getText() + btn_four.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fourActionPerformed

    private void btn_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fiveActionPerformed
        String Enternumber = txt_result.getText() + btn_five.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fiveActionPerformed

    private void btn_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sixActionPerformed
        String Enternumber = txt_result.getText() + btn_six.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sixActionPerformed

    private void btn_sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sevenActionPerformed
        String Enternumber = txt_result.getText() + btn_seven.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sevenActionPerformed

    private void btn_nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nineActionPerformed
        String Enternumber = txt_result.getText() + btn_nine.getText();
        txt_result.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nineActionPerformed

    private void btn_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumActionPerformed
        firstnum = Double.parseDouble(txt_result.getText());
        txt_result.setText("");
        operations="+";
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sumActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
         txt_result.setText("");
         // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restActionPerformed
        firstnum = Double.parseDouble(txt_result.getText());
        txt_result.setText("");
        operations="-";
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_restActionPerformed

    private void btn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiActionPerformed
        firstnum = Double.parseDouble(txt_result.getText());
        txt_result.setText("");
        operations="*";
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_multiActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_result.setText("");
        txt_formula.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_divi;
    private javax.swing.JButton btn_eight;
    private javax.swing.JButton btn_equal;
    private javax.swing.JButton btn_five;
    private javax.swing.JButton btn_four;
    private javax.swing.JButton btn_multi;
    private javax.swing.JButton btn_nine;
    private javax.swing.JButton btn_one;
    private javax.swing.JButton btn_point;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_rest;
    private javax.swing.JButton btn_seven;
    private javax.swing.JButton btn_six;
    private javax.swing.JButton btn_sum;
    private javax.swing.JButton btn_three;
    private javax.swing.JButton btn_two;
    private javax.swing.JButton btn_zero;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_formula;
    private javax.swing.JTextField txt_result;
    // End of variables declaration//GEN-END:variables
}
